# Generated by Django 5.0.2 on 2024-02-24 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, default='+78', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Формат телефонного номер должен быть +79999999999', regex='^\\+?1?\\d{11}$')]),
            preserve_default=False,
        ),
    ]
