# Generated by Django 5.0.2 on 2024-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
    ]
