# Generated by Django 5.0.2 on 2024-03-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_options_alter_message_options_and_more'),
        ('client', '0002_alter_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Отправитель'),
            preserve_default=False,
        ),
    ]
